### ISSUE TITLE
[FEATURE] Walk speed toggle?

### ISSUE THREAD

**Issue by BlueYoshi68** [CorneliusCornbread/Crawl-Speed-Toggle#1]
I'd literally NEED this exact thing, but for walking instead of crawling

**Comment by CorneliusCornbread** [comment]
Do you want it to use the world's set walk speed or some speed in between walking and crawl speed?

**Comment by BlueYoshi68** [comment]
prolly the world walk speed, so i can use it viably in game worlds

**Comment by BlueYoshi68** [comment]
Anything yet?

**Comment by CorneliusCornbread** [comment]
Added in 1.1.0
